### ISSUE TITLE
libinotifytools doesn't handle very long filenames

### ISSUE THREAD

**Issue by 813gan** [inotify-tools/inotify-tools#107]
At the moment libinotifytools silently truncates very long strings. According to [Wikipedia](https://en.wikipedia.org/wiki/Comparison_of_file_systems#Limits) most file systems doesn't have defined maximal filename length so it's necessary to store filenames in dynamically allocated memory.

**Comment by ericcurtin** [comment]
Good idea, 4095 is generally seen as the max path length in Unix. In Linux it's defined in 

/usr/include/linux/limits.h

```
  #define NAME_MAX         255    /* # chars in a file name */
  #define PATH_MAX        4096    /* # chars in a path name including nul */
```

Lots of user-space tools will start to fail after this limit on many platforms, we wouldn't be alone here. But theoretically some filesystems on Linux and other platforms will support longer lengths.

If it's theoretically possible we should try and use dynamic strings :)
