### ISSUE TITLE
monitor file ownership change

### ISSUE THREAD

**Issue by qiulang** [inotify-tools/inotify-tools#112]
Hi, this is a question more than a feature request because I do not know whether it can be done or not and I also don't know where I can ask this question. 

Sorry if I ask a dumb question. So is it possible to monitor file ownership change ?

My use case is this, my web-app runs inside docker and when Devops guys log inside docker to check the system, they always forgot they log inside docker using **root** (normally they just run `docker exec container_id /bin/bash`), so when they make a change to a file, the file ownership will be changed from `www-data` to `root`. They always forgot to change it back, then that causes all kinds of problem.

So I am thinking about writing a script to monitor some specific files, whenever their ownerships changed the script will change them back. 

But I am not whether that can be done or not. I asked the same question at SO and the question was downvoted. So I asked here, hoping I can get some reply.

Thanks a lot!

**Comment by ericcurtin** [comment]
Don't worry about it 😄 

Yeah sure it can be done, I even wrote an integration test for this to be 100% sure here:

8967735d3a17ced1aa8e0093f8187f89c4e93770

You can track chown just fine using inotify-tools,

A silly example in bash would be:

```
#!/bin/bash

while true; do
  inotifywait -e attrib some_filename
  printf "Some attribute in some_filename has changed, print this"
done

```
