### ISSUE TITLE
Release Schedule

### ISSUE THREAD

**Issue by tcf909** [inotify-tools/inotify-tools#115]
Hello,

Could you shed some light on inotify releases in upstream?

We run mostly Debian and do our best to stick to officially supported repos. 

Trying to understand how and when latest commits to master will make it upstream.

Thanks

**Comment by ericcurtin** [comment]
I don't actually have one, it's ad-hoc but now that you say it, maybe I should create one :smile:

Let's say it's quarterly so the next one will be in September, then December, March, June.
