### ISSUE TITLE
inotifywait times out immediately

### ISSUE THREAD

**Issue by eater** [inotify-tools/inotify-tools#117]
**Describe the bug**

I've been using inotifywait to watch directories on my Ubuntu 18.04 laptop. Today, I didn't change anything, but when I launch inotifywait (even with the `-m` flag), it says "Watches established" and then exits with exit code 2 without reporting an event.

**To Reproduce**
1. From command line, run `inotifywait -mr /home/eater/testdir`
2. Observe that after setting up watches, the process immediately exits: 
`Setting up watches.  Beware: since -r was given, this may take a while!
Watches established.`
3. Check the exit code with `echo $?`
4. Observe response of `2`.

**Expected behavior**
Inotifywait should wait indefinitely for an event.

**Desktop (please complete the following information):**
 - OS: Ubuntu Linux 18.04
 - Version: 3.14 (via Ubuntu repository)

**Additional context**
This behavior was not happening until today. I just tried uninstalling and reinstalling the inotify-tools package but that didn't make a difference.

**Comment by ericcurtin** [comment]
Could you try the master version? Couldn't reproduce myself, that always makes it an issue for me attempting to fix. Good start though, we have hit a EXIT_TIMEOUT which is a 2

**Comment by eater** [comment]
Master version works great!

**Comment by ericcurtin** [comment]
Oh cool, may have been fixed already, would you mind if I closed this @eater?

**Comment by eater** [comment]
Yeah, still working fine today.
