### ISSUE TITLE
The `inotifywait` processes remain running after starting `./build_and_test`

### ISSUE THREAD

**Issue by 3ap** [inotify-tools/inotify-tools#119]
**Describe the bug**
`./build_and_test` produces `inotifywait` processes for testing purpose but it doesn't kill these processes properly

**To Reproduce**
1. Run `./build_and_test`
2. Wait for the end of execution
3. Run `ps -ef | grep inotifywait`
4. See at least two remaining processes:
```
zar        50443       1  0 19:30 ?        00:00:00 ../../src/.libs/inotifywait --monitor --daemon --quiet --outfile log --format %c %e %w%f --event create --event moved_to --event moved_from /home/zar/inotify-tools/t/trash.directory.inotifywait-format-option-cookie
zar        53111       1  0 19:30 ?        00:00:00 ../../src/.libs/inotifywait --monitor --daemon --quiet --outfile log --format %c %e %w%f --event create --event moved_to --event moved_from /home/zar/inotify-tools/t/trash.directory.inotifywait-format-option-cookie
```

**Expected behavior**
There are no redundant processes after execution

**Desktop:**
 - OS: Arch Linux
 - Version: master branch

**Comment by ericcurtin** [comment]
Fixed by 0da6b4e66319243b2ebb788f3839e849f8557d75

Thanks for reporting
