### ISSUE TITLE
inotifywait: improve implementation of `--monitor --recursive`

### ISSUE THREAD

**Issue by mikkorantalainen** [inotify-tools/inotify-tools#121]
**Is your feature request related to a problem? Please describe.**
The manual page already describes some limitations of `inotifywait -r` flag. However, it fails to mention that if a new subdirectory is created and new files or directories have been created inside it very fast, inotifywait will fail to notice those files.

**Describe the solution you'd like**
inotifywait is already able to notice the newly created directory within already watched hierarchy. After creating a new ionitify watch for the newly created directory, inotifywait should scan the directory once and emit a synthetic create event for each file and directory recursively. This would result in inotifywait always reporting at least one event for every new file and directory recursively even if creating those files happened faster than inotify watches could be added.

I would suggest adding a new event type `CREATE_SYNTHETIC` (feel free to come up with a better event name) and always emit that event for every file and directory scanned within a new directory to avoid having to filter files and directories created after the directory watch has already established. (That is, this event may be emitted in addition to events the inotifywait already emits.)

Another event worth considering is `ESTABLISHED` which would be emitted once for each directory after successfully adding inotify watch for that directory. That would allow scripts to have a solid knowledge of the time that any given directory is fully monitored. Note that the recursive scanning of the directory contents for synthetic events should be done after emitting the `ESTABLISHED` event so that no new files can appear between scanning and watching for changes (this avoids races with rapidly modified subtree getting totally missed). 

A related improvement would be to emit `INITIAL_ESTABLISHED` for the root directory once all recursive watches have been added after starting `inotifywait -r`. That would allow scripts to correctly detect the moment of time the watches have been fully established. Currently inotifywait only emits a user visible message for this event.

Obviously, without `-m` emitting these extra events really doesn't make any sense.

**Describe alternatives you've considered**
Simply improving the `man inotifywait` to describe this additional limitation.

**Additional context**
Background info: I noticed this issue by removing a complex subdirectory in source code and then doing git reset --hard to restore it. Because git is very fast to modify files and directories, `inotifywait -r` failed to notice some subdirectories and files created by git.

**Comment by ericcurtin** [comment]
Yeah git is very demanding on the file system alright, it's part of the reason it's so fast. Using git shares on networked drives like NFS requires tweaking sometimes to keep it super fast, if you are used to using git on local drives.

Anyway... I'm not opposed to any of these changed. Sounds good!

**Comment by mikkorantalainen** [comment]
Yeah, I'm using git on local SSD + lots of RAM cache so I'm expecting pretty fast experience. I'm trying to use inotifywait to automatically synchronize changes to remote test machine as soon as possible. Some `bash` scripting + `inotifywait` seems to work great except with bigger changes where inotifywait seems to lose some events due problems described above. I'm currently doing full `rsync` after syncronizing all detected changes to fix any lost changes. Full rsync causes maybe 2 second extra delay. With the above changes, I wouldn't need to run full `rsync` at all.

**Comment by ericcurtin** [comment]
You could actually git push or pull to that target you are trying to get to (over ssh) in order to achieve your goals. Lily would be faster vs rsync, git does some pretty good compression and deltas

**Comment by mikkorantalainen** [comment]
I'm using the script located at https://github.com/mikkorantalainen/rsync-continuous which runs extra rsync on the background as workaround after syncing all the modified files.

Syncing all the modified files that inotify-tools notices is actually faster than using git because git always does full FS scan and with a big repository that's slow enough to matter. The background sync for missed files rarely finds anything to do but will fix the issue in case inotify-wait missed some change.

Note that the default kernel limits for inotify watches are really low and the above script will not work unless you tweak the kernel limits, too.

# # increase inotify limits
# echo 1000000 > /proc/sys/fs/inotify/max_queued_events
# echo 1000000 > /proc/sys/fs/inotify/max_user_instances
# echo 1000000 > /proc/sys/fs/inotify/max_user_watches

**Comment by ericcurtin** [comment]
> Syncing all the modified files that inotify-tools notices is actually faster than using git because git always does full FS scan and with a big repository that's slow enough to matter.

Yeah I've encountered this shares, I've done tricks like adding:

```
[status]
        showUntrackedFiles = no
```

to ~/.gitconfig to make things faster for `git status` for example, it doesn't check for new files then, unless you `git add` them.

> Simply improving the man inotifywait to describe this additional limitation.

Sounds like a good idea
