### ISSUE TITLE
Annotated Tags Please

### ISSUE THREAD

**Issue by emontellese** [inotify-tools/inotify-tools#124]
Suggestion / Request to use annotated tags for version tag numbers.  

This is considered "best practice" by a number of open source projects and annotated tags have a number of advantages for official releases.

For our purposes, it will simplify the way that we use 'git describe' to collect information about packages that are a part of our build.  By default, git describe ignores "lightweight tags"

Many thanks!

**Comment by ericcurtin** [comment]
Done:

```
#!/bin/bash
  
set -e

git for-each-ref refs/tags | grep commit | while read -r i; do
  tag=$(echo "$i" | awk -F"/" '{printf $NF"\n"}')
  echo "Creating $tag"
  git tag -a -f "$tag" "$tag" -m ""
  echo "Pushing $tag"
  git push -f origin "$tag"
done
```

**Comment by ericcurtin** [comment]
Who is "our" by the way @emontellese ? I'm thinking of compiling a list of of companies/orgs/projects that use this tool

**Comment by emontellese** [comment]
Many thanks!  "Our" in this case is Netgear for some code / products still in development.  Look for more info about these projects from Netgear in the months to come :)

**Comment by ericcurtin** [comment]
Ah yes, I've had a netgear router or two in the past, good to know!
