### ISSUE TITLE
Install instructions: suggest to run ./autogen.sh before ./configure

### ISSUE THREAD

**Issue by jeff47** [inotify-tools/inotify-tools#125]
This is probably not a true bug report, but I think it is an issue in the docs at least.

It is stated to install on ubuntu, start with "./configure".  However, I think it is necessary to execute "./autogen.sh" first, otherwise there is no configure script to run.

**Comment by ericcurtin** [comment]
Made the wiki change:

https://github.com/inotify-tools/inotify-tools/wiki/Home/9f36fcbab6e8460bd368e5554df937a9a90a40a8

**Comment by jeff47** [comment]
Sorry, I wasn't clear.  I suggest updating the instructions in INSTALL (https://github.com/inotify-tools/inotify-tools/blob/master/INSTALL) as well.

**Comment by ericcurtin** [comment]
Oh ok, it's done:

9fe9927eb33714a75d95b7556eee3a876b49e446
