### ISSUE TITLE
usr/local/bin/inotifywait: symbol lookup error: /usr/local/bin/inotifywait: undefined symbol: inotifytools_ignore_events_by_inverted_regex

### ISSUE THREAD

**Issue by zwx168238** [inotify-tools/inotify-tools#128]
**Describe the bug**
usr/local/bin/inotifywait: symbol lookup error: /usr/local/bin/inotifywait: undefined symbol: inotifytools_ignore_events_by_inverted_regex

**To Reproduce**
Pre-requisites
==============
Install autoconf, on Ubuntu:

 sudo apt-get install autoconf

then install automake, on Ubuntu:

 sudo apt-get install autotools-dev
 sudo apt-get install automake

then install libtool, on Ubuntu:

 sudo apt-get install libtool

Now you can proceed with basic intallation:
./autogen.sh
./configure 
make
sudo make install

**Expected behavior**
run usr/local/bin/inotifywait

**Screenshots**
symbol lookup error: /usr/local/bin/inotifywait: undefined symbol: inotifytools_ignore_events_by_inverted_regex

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04.1 LTS

**Additional context**
NA

**Comment by zwx168238** [comment]
ldd -r /usr/local/bin/inotifywait 
        linux-vdso.so.1 (0x00007ffde2d34000)
        libinotifytools.so.0 => /lib/x86_64-linux-gnu/libinotifytools.so.0 (0x00007f6f35bec000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f6f359fa000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f6f35c27000)
undefined symbol: inotifytools_ignore_events_by_inverted_regex  (/usr/local/bin/inotifywait)

**Comment by zwx168238** [comment]
```
 /usr/bin/mkdir -p '/usr/local/lib'
 /bin/bash ../../libtool   --mode=install /usr/bin/install -c   libinotifytools.la '/usr/local/lib'
libtool: install: /usr/bin/install -c .libs/libinotifytools.so.0.4.1 /usr/local/lib/libinotifytools.so.0.4.1
libtool: install: (cd /usr/local/lib && { ln -s -f libinotifytools.so.0.4.1 libinotifytools.so.0 || { rm -f libinotifytools.so.0 && ln -s libinotifytools.so.0.4.1 libinotifytools.so.0; }; })
libtool: install: (cd /usr/local/lib && { ln -s -f libinotifytools.so.0.4.1 libinotifytools.so || { rm -f libinotifytools.so && ln -s libinotifytools.so.0.4.1 libinotifytools.so; }; })
libtool: install: /usr/bin/install -c .libs/libinotifytools.lai /usr/local/lib/libinotifytools.la
libtool: install: /usr/bin/install -c .libs/libinotifytools.a /usr/local/lib/libinotifytools.a
libtool: install: chmod 644 /usr/local/lib/libinotifytools.a
libtool: install: ranlib /usr/local/lib/libinotifytools.a
libtool: finish: PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin:/sbin" ldconfig -n /usr/local/lib
----------------------------------------------------------------------
Libraries have been installed in:
   /usr/local/lib

If you ever happen to want to link against installed libraries
in a given directory, LIBDIR, you must either use libtool, and
specify the full pathname of the library, or use the '-LLIBDIR'
flag during linking and do at least one of the following:
   - add LIBDIR to the 'LD_LIBRARY_PATH' environment variable
     during execution
   - add LIBDIR to the 'LD_RUN_PATH' environment variable
     during linking
   - use the '-Wl,-rpath -Wl,LIBDIR' linker flag
   - have your system administrator add LIBDIR to '/etc/ld.so.conf'

See any operating system documentation about shared libraries for
more information, such as the ld(1) and ld.so(8) manual pages.
----------------------------------------------------------------------
```
解决方法
export LD_LIBRARY_PATH=/home/other/test/lib:$LD_LIBRARY_PATH

**Comment by zwx168238** [comment]
已经找到解决办法 应该是使用了默认的安装路径 导致ldd查找不到默认安装里面的库文件

**Comment by ericcurtin** [comment]
The default for any autotools built tool is /usr/local which kind of sucks for libraries as it's normally not in the dynamic linking library path. To changes this to /usr:

./autogen.sh
./configure --prefix=/usr
make
sudo make install

**Comment by ericcurtin** [comment]
https://github.com/inotify-tools/inotify-tools/commit/7b3d4ff09b2ab845782c144455e6181f97171c0a#diff-b83b327f0b62e8168163c61f15fb0ac2c14169729e4f4184678337a15cd04dec

**Comment by shorca** [comment]
My apologies, problem gone if I restart the bash. Thanks!
