### ISSUE TITLE
reduction of CPU load

### ISSUE THREAD

**Issue by herrdeh** [inotify-tools/inotify-tools#135]
**Is your feature request related to a problem? Please describe.**
My script (see attachments) used to sort downloads to several directories eats up as much as 12% CPU due to TOP.

**Describe the solution you'd like**
Does it make sense to introduce an option to limit the number of checks per second carried out ? - For such a vanilla task 1-2 checks per second would be good enough.

**Describe alternatives you've considered**
nice -19 didnt make any change.

**Additional context**
Could well be the case that this option already is available, and the dummy user could not find it - in this case a hint would be great! Any other hints to improve this script also are very welcome!

[Inotify-Downloads-sortieren.txt](https://github.com/inotify-tools/inotify-tools/files/6205116/Inotify-Downloads-sortieren.txt)

**Comment by ericcurtin** [comment]
> nice -19 didnt make any change.

Is your CPU under load, do other processes require CPU cycles? If no, it makes sense that inotifywait uses a little CPU. Priority != CPU usage.

> Does it make sense to introduce an option to limit the number of checks per second carried out ? - For such a vanilla task 1-2 checks per second would be good enough.

Why not? :) If we don't break backwards compatibility I'm happy. But I wonder should we consider things like io_uring, select, epoll, poll, other event loops, kernel tweaks, etc.

https://github.com/shuveb/io_uring-by-example

**Comment by herrdeh** [comment]
Thank you for your attention.  But sorry, I'm just a dumb user and do hardly understand anything of your writing. All I can contribute is the observation that inotifywait seems (I'm not really sure about that) to consume much more ressources than it actually needs to. My guess is that this leads to a waste of electricity and unnecessary thermal load, I'd like to have that avoided, and I believe in some kind of "global responsibility" in these things.

I'd like to see inotifywait to be used widely (would file a RFE in GNOME for a inotify-GUI), but it should not ramp up power consumption more than necessary.

**Comment by ericcurtin** [comment]
I agree with most of your points, except for the one that you are a dumb user :smile: 

I'm always happy to see contributions in any of these areas... but... and this is the key point, we can't break any pre-existing functionality.

**Comment by herrdeh** [comment]
So I think I made my point clear: inotify is a really great feature which deserves much more use. But it may be worth to think whether it may consume more power than necessary - and which is the best solution for that issue.

**Comment by ericcurtin** [comment]
`-S, --sleep-interval=N` works for me if anyone picks this up

**Comment by herrdeh** [comment]
Am Donnerstag, den 22.04.2021, 05:47 -0700 schrieb Eric Curtin:
> -S, --sleep-interval=N works for me if anyone picks this up
>
As mentioned before: I'm just a dump user. How precisely do you apply
the "sleep" option?
