### ISSUE TITLE
inotifywait exits if watched file does not exist at startup

### ISSUE THREAD

**Issue by smalers** [inotify-tools/inotify-tools#136]
I am using `inotifywait` 3.14 on Debian to watch for compiled executable programs to be updated, which results in the files being copied to a test virtual machine with deployed environment for testing.  This allows me to avoid building an installer during development.  The development environment and deployed environment have different file locations so we have a CSV file to map source and destination.  The problem is that in some cases, a source file may not exist when the `inotifywait` program is started and a warning like the following is shown:

```
Couldn't watch somefile: No such file or directory
```

My request is that functionality is added that would optionally allow the program to start even if watched resources don't exist.  From the documentation it does not seem that there is such functionality.  The parent directory could be watched, but this complicates the 1-to-1 mapping of specific files.

**Comment by ericcurtin** [comment]
Cool idea, pull requests welcome

**Comment by mb720** [comment]
Although I can't offer a PR, I'd like to second this.

As an extension, it would be very useful to be able to watch directories that don't exist when inotifywait starts.

For example, I'd like to get notified when files are added to the mount directory `/run/media/me`, e.g, when partitions are mounted via [udiskie](https://github.com/coldfix/udiskie). That directory doesn't exist on my system after boot, but `/run/media/` does.

What I tried is this:

    inotifywait --monitor --recursive /run/media/ -e create |
        while read path action file; do
            echo "The file '$file' appeared in directory '$path' via '$action'"
        done

This gives a notification that the directory `me` was created inside `/run/media` once a partition (let's call it `my_partition`) is mounted. But crucially, I *don't* get a notification that `my_partition` now exists.
