### ISSUE TITLE
inotifywait keep watch on files out of scope after moving parent directory 

### ISSUE THREAD

**Issue by llusca** [inotify-tools/inotify-tools#137]
**Describe the bug**
Inotifywait keep watch on files after moving parent directory out of directory scoped (MOVE_SELF).

**To Reproduce**
1. mkdir -p mkdir -p test/to_watch/to_move/dir
2. inotifywait -rm test/to_watch/
3. echo hello >> test/to_watch/to_move/dir/testfile
test/to_watch/to_move/dir/ CREATE testfile
test/to_watch/to_move/dir/ OPEN testfile
test/to_watch/to_move/dir/ MODIFY testfile
test/to_watch/to_move/dir/ CLOSE_WRITE,CLOSE testfile
**OK**
4.mv test/to_watch/to_move test
test/to_watch/ MOVED_FROM,ISDIR to_move
test/to_watch/to_move/ MOVE_SELF 
**testfile out of scope**
5.echo hello >> test/to_move/dir/testfile 
test/to_watch/to_move/dir/ OPEN testfile
test/to_watch/to_move/dir/ MODIFY testfile
test/to_watch/to_move/dir/ CLOSE_WRITE,CLOSE testfile
**Nothing should be watched**

ls -R test/
test/:
to_move  to_watch

test/to_move:
dir

test/to_move/dir:
testfile

test/to_watch:

**Expected behavior**
At stage 5, nothing should be watched (because parent directory is out of scope).

**Desktop (please complete the following information):**
 - OS: debian
 - Version 10

**Comment by ericcurtin** [comment]
Thanks for reporting! I'm guessing it's because we are inode based rather than filename based. So when you mv the file, the inode doesn't change.

**Comment by llusca** [comment]
Maybe you should construct a list of watches whose filename begins by the moved one's. Then remove them from rbtree.

**Comment by ericcurtin** [comment]
#130 is linked I believe
