### ISSUE TITLE
inotiywait not detecting changes to folders in monitored paths containing bind mounts

### ISSUE THREAD

**Issue by ioogithub** [inotify-tools/inotify-tools#139]
**Describe the bug**
inotiywait not detecting changes to subfolders that are bind mounted.

**To Reproduce**

1. Setup inotifywait on /path:
`
$ inotifywait /path -e modify,create,moved_to,close_write,delete -r
`

2. /path/subfolder i bind mounted to another location (/mnt/subfolder):
`
`$ su -Mc mount -o bind /mnt/subfolder /path/subfolder`
`

**Expected behavior**
inotifywait will detect any changes in the entire /path including in the /path/subfolder as this is the intention of a bind mount.

**Desktop (please complete the following information):**
 - OS: LineageOS 17.1
 - Version: inotifywait 3.20.2.2 (termux version)

**Smartphone (please complete the following information):**
 - Device: Moto G7+
 - OS: Android 10
 
**Additional context**
inotifywait is not detecting changes made in a monitored path containing a bind mounted subfolder. In this case I must use a bind mount as opposed to a symlink as the filesystem I am monitoring does not support symlinks.

**Comment by ioogithub** [comment]
After additional testing the issue was Android related, inotifywait is working as expected.

Thank you for this awesome piece of code.

**Comment by ericcurtin** [comment]
I'm just happy to know these tools work on Android. Admittedly we don't actively test there. So that's nice to know :+1: I depend on the CI infrastructure and a handful of instances I have myself.
