### ISSUE TITLE
API changes from "const char*" to "char*" breaks applications

### ISSUE THREAD

**Issue by sgh** [inotify-tools/inotify-tools#147]
Commit f766860180e39291d407b4b9cdc74e95e50b114e changes a lot of functions to take char* even though the functions themselves to not modify the strings. Why has this change been done, I assume that you know that it will break compiling applications passing in "const char*" into those functions.

**Comment by ericcurtin** [comment]
Fixed

**Comment by sgh** [comment]
thanks
