### ISSUE TITLE
Add a truly quiet mode to inotifywait

### ISSUE THREAD

**Issue by Ingvix** [inotify-tools/inotify-tools#151]
For my purpose use case, I only need to know when a file gets modified so I run inotifywait in a loop with what needs to be done when the monitored file gets modified. I have no use for the output line so it'd be nice if I could get rid of it altogether. I tried setting `--format` to an emptry string with `--no-newline` but inotifywait wasn't having it. Not a truly necessary feature as I can redirect the output to /dev/null but nonetheless it would make this a slightly less complex.

**Comment by ericcurtin** [comment]
Code contributions welcome, just add a new command line option so we have backwards compatibility

**Comment by ericcurtin** [comment]
And tests of course
