### ISSUE TITLE
move a folder that includes more than 5000 files

### ISSUE THREAD

**Issue by kill322003** [inotify-tools/inotify-tools#152]
Error occured "Segmentation fault (core dumped)",when move a folder that includes more than 5000 files.

**Comment by ericcurtin** [comment]
Could you detail steps taken to reproduce or post a backtrace here?

**Comment by kill322003** [comment]
![steps](https://user-images.githubusercontent.com/31067097/144595506-7f026ddf-e1ef-4ffa-86c2-c9cca38712ed.png)
![error](https://user-images.githubusercontent.com/31067097/144595595-16a02c6a-d8eb-4a5a-820f-fc20cf079843.png)

**Comment by kill322003** [comment]
![trace](https://user-images.githubusercontent.com/31067097/144595965-319dd7e9-ff37-48cd-86ab-5f89ad3a74d4.png)

**Comment by ericcurtin** [comment]
Hmmmm, is this the RHEL 7 version installed via yum? If yes that's quite old the bug may not even exist anymore. Would you like the build the master branch in this repo and run with the binaries with debugging symbols on to see if it still exists in the latest version? Build steps:

  export CC="gcc"
  export CFLAGS="-O0 -ggdb"
  export LDFLAGS="-O0 -ggdb"
  ./autogen.sh
  ./configure --prefix=/usr
  make

and then to install these latest binaries:

  sudo make install

And if it reproduces post the backtrace with the function names here. And if it doesn't reproduce well you have a solution then use the latest version :smile:

**Comment by kill322003** [comment]
ok，I will try it.Thank you very much!

**Comment by kill322003** [comment]
the latest version is ok。3ks。
