### ISSUE TITLE
Output now shows the directory of the watched file.

### ISSUE THREAD

**Issue by auouymous** [inotify-tools/inotify-tools#157]
`inotifywait -q /var/log/everything/current` used to output `/var/log/everything/current MODIFY` but now outputs `/var/log/everything/ MODIFY`.

From man page:
```
The  event  output can be configured, but by default it consists of lines of the following form:

       watched_filename EVENT_NAMES event_filename
```

Is this a bug or does the man page need to be updated to reflect new behavior?

**Comment by ericcurtin** [comment]
How exactly was this reproduced? What 2 versions are we comparing?

**Comment by auouymous** [comment]
It is reproduced by running inotifywait on a file and then writing to that file in another terminal. And if the file lacks a directory path, such as with `inotifywait foo`, only ` MODIFY` is output.

97a3525280f3b91a0c3abc1fdc89cba6da957a6b is the last good commit and 698012176ac333c62f80190d6760a4fae5cffffb is the first testable bad commit. The 12 commits between those two won't compile for me.

**Comment by ericcurtin** [comment]
Could you cherry-pick https://github.com/inotify-tools/inotify-tools/commit/698012176ac333c62f80190d6760a4fae5cffffb on top of all the commits in between to find the actual commit where this behaviour changed?

**Comment by ericcurtin** [comment]
Wish @vitaut had a C version of libfmt to solve silly issues like fixed in commit 6980121

**Comment by ericcurtin** [comment]
And could you try the one-line change in https://github.com/inotify-tools/inotify-tools/tree/disable_fanotify branch?

Seeing that your build wasn't working suggests that you are using the new fanotify interface vs inotify interface in the good commit you mentioned.

**Comment by auouymous** [comment]
0971a971bb05287efae1aea9a2a28bdbc3351f78 is the commit causing the missing filename in output.

I don't know what one-line change you are referring to, but the disable_fanotify branch is also missing the filename in output.

**Comment by auouymous** [comment]
The disable_fanotify branch appears to be identical to master branch.

**Comment by ericcurtin** [comment]
Sorry yes, try the disable_fanotify branch now, it removes most of the code introduced by 0971a97

**Comment by ericcurtin** [comment]
Forgot to push the commit, spinning a few plates at work

**Comment by ericcurtin** [comment]
If that works @auouymous , I will change fanotify to be off by default for now.

**Comment by auouymous** [comment]
The disable_fanotify branch is still missing the filename.

**Comment by ericcurtin** [comment]
Would you mind hunting that down @auouymous ? So we can revert back to the old behaviour?

**Comment by auouymous** [comment]
The following two hunks in 0971a971bb05287efae1aea9a2a28bdbc3351f78 are the cause of the problem and it should be an issue for everyone, unless I'm reading the code wrong. Does it show the full filename for you?

The new `inotifytools_dirname_from_event()` sets dirnamelen to the length up to the last `/`. And the `%w` format specifier now uses dirnamelen to only show up to that last `/`, chopping off the file's name after it. That new function is also called from `output_event_csv()` to chop off the file's name.

I don't use fanotify because #134 mentions >=5.9 is required and I have 5.4. Maybe fanotify always returns the file's name in `event->name` for all events and would show up as `dir/ MODIFY file` when watching `dir/file`, and that was the reason why @amir73il  clipped off the file's name and changed the behavior of `%w`.

```patch
@@ -1578,8 +2034,8 @@ int inotifytools_snprintf( struct nstring * out, int size,
        eventname = NULL;
    }
 
-
-   filename = inotifytools_filename_from_wd( event->wd );
+   size_t dirnamelen = 0;
+   filename = inotifytools_dirname_from_event(event, &dirnamelen);
 
    if ( !fmt || 0 == strlen(fmt) ) {
        error = EINVAL;
@@ -1625,9 +2081,9 @@ int inotifytools_snprintf( struct nstring * out, int size,
        }
 
        if ( ch1 == 'w' ) {
-           if ( filename ) {
-               strncpy( &out->buf[ind], filename, size - ind );
-               ind += strlen(filename);
+           if (filename && dirnamelen <= size - ind) {
+               strncpy(&out->buf[ind], filename, dirnamelen);
+               ind += dirnamelen;
            }
            ++i;
            continue;
```

**Comment by amir73il** [comment]
Thanks for the detailed analysis @auouymous I seem to have overlooked the case of watching a single file
and I guess none of the tests provide coverage for this issue.
I will fix it up and add test coverage

**Comment by ericcurtin** [comment]
Thanks very much @amir73il
