### ISSUE TITLE
Unable to listen for mariadb database file changes

### ISSUE THREAD

**Issue by qqliuxiaoran** [inotify-tools/inotify-tools#161]
`students.ibd` is my `mariadb` database file
```
[root@ha-slave students]# ll
-rw-r--r-- 1 root    root        0 3月   8 10:25 1.txt
-rw-rw---- 1 sac_mdb sac_mdb    65 3月   7 20:06 db.opt
-rw-rw---- 1 sac_mdb sac_mdb  1170 3月   7 20:06 students.frm
-rw-rw---- 1 sac_mdb sac_mdb 98304 3月   8 10:25 students.ibd
```
Then input inotifywait command
```
inotifywait -rm --timefmt "%d/%m/%y %H:%M:%S" --format '%T %e %w %f' -e "create,modify,close_write,delete,attrib,move" .
```
Then input the following command in another shell window at this dir
```
touch 2.txt
```
inotifywait print as follow
```
Setting up watches.  Beware: since -r was given, this may take a while!
Watches established.
08/03/22 10:30:24 CREATE ./ 2.txt
08/03/22 10:30:24 ATTRIB ./ 2.txt
08/03/22 10:30:24 CLOSE_WRITE,CLOSE ./ 2.txt
```
Then i connect my db and input a insert SQL like `insert students(student_name,student_address)values('jack','xxxx');`
```
-rw-rw---- 1 sac_mdb sac_mdb 98304 3月   8 10:31 students.ibd
```
Database file is changed but inotifywait print nothing，how can i do? thank you!

**Comment by auouymous** [comment]
I successfully ran the same command on mysql and sqlite databases.

What version do you have?

**Comment by qqliuxiaoran** [comment]
> I successfully ran the same command on mysql and sqlite databases.
> 
> What version do you have?

inotifywait 3.20.11.0. sorry for my late

**Comment by qqliuxiaoran** [comment]
Now i use latest version but not solve the problem, maybe `MariaDB` is special?

**Comment by qqliuxiaoran** [comment]
> Try it without the `-e "create,modify,close_write,delete,attrib,move"`, does it produce any events?

Produce no event
