### ISSUE TITLE
undefined symbol: inotifytools_filename_from_event

### ISSUE THREAD

**Issue by de-gozaru** [inotify-tools/inotify-tools#162]
Hi guys,

I'm trying to install inotify-tools on an ubuntu machine 20.04.

I tried first to use install it using
```
sudo apt-get install inotify-tools
```
but I got the error:
```
Couldn't initialize inotify. Are you running Linux 2.6.13 or later, and was the CONFIG_INOTIFY option enabled when your kernel was compiled? If so, something mysterious has gone wrong. Please e-mail radu.voicilas@gmail.com and mention that you saw this message.
```
Since I couldn't find a solution to this problem, I'm trying to install it from source, version `3.22.1.0`, I used the following steps:
```bash
./autogen.sh
./configure --prefix=/usr --libdir=/lib64
make
make check  # the test passes
sudo make install
```
during the last step, I got the following warnings:
```bash
[...]
libtool: warning: remember to run 'libtool --finish /directory/lib'
[...]
make[2]: Entering directory '/home/vongola/Downloads/inotify-tools-3.22.1.0/src'
 /usr/bin/mkdir -p '/usr/bin'
  /bin/bash ../libtool   --mode=install /usr/bin/install -c inotifywait inotifywatch '/usr/bin'
libtool: warning: '../libinotifytools/src/libinotifytools.la' has not been installed in '/directory/lib'
libtool: install: /usr/bin/install -c .libs/inotifywait /usr/bin/inotifywait
libtool: warning: '../libinotifytools/src/libinotifytools.la' has not been installed in '/directory/lib'
libtool: install: /usr/bin/install -c .libs/inotifywatch /usr/bin/inotifywatch
```
so I ran the command
```bash
libtool --finish /directory/lib
```

But in vain, since when I run `inotifywait`, I got:
```bash
inotifywait: symbol lookup error: inotifywait: undefined symbol: inotifytools_filename_from_event
```

How can I solve this please?

Thank you in advance!

**Comment by ericcurtin** [comment]
The first problem "apt-get", I can't help with the debian/ubuntu package needs to be updated that's really old.

Could you run "ldd /usr/bin/inotifywait" and send me the output?

**Comment by de-gozaru** [comment]
Hi @ericcurtin 

Thank you for your response.

Here is the output:
```bash
ldd /usr/bin/inotifywait                                                     
          linux-vdso.so.1 (0x00007ffe4f5e9000)
          libinotifytools.so.0 => /lib/x86_64-linux-gnu/libinotifytools.so.0 (0x00007efc11fde000)
          libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007efc11dec000)
          /lib64/ld-linux-x86-64.so.2 (0x00007efc1203e000)
```

**Comment by ericcurtin** [comment]
And if you look at the /lib/x86_64-linux-gnu/libinotifytools.so.0 library and related symlinks does the date/time change when you run your `sudo make install`

It appears as though you are trying to use the `apt-get` lib with the `make install` binary

An `apt-get remove inotify-tools` (or whatever the correct command is might help ensure you are running the correct binary and lib combination.

**Comment by de-gozaru** [comment]
Hi @ericcurtin 
Actually, I made sure that I removed the package installed via apt-get.

For the first remark, indeed, running the following command
```bash
stat -c '%y' /lib/x86_64-linux-gnu/libinotifytools.so.0                                          
2019-08-06 18:42:10.000000000 +0200
```
It seems that the symlink is old, am I doing something wrong during the installation?

It should be noted that I downloaded the tar.gz from github, extract it in my download folder, and followed the steps I described above!

**Comment by ericcurtin** [comment]
Just ran this in a brand new ubuntu 20.04 instance:

```
./autogen.sh
./configure --prefix=/usr
make -j8
sudo make install
```

worked perfect, could you try that?

**Comment by ericcurtin** [comment]
As documented here:

https://github.com/inotify-tools/inotify-tools/blob/master/INSTALL

**Comment by de-gozaru** [comment]
Hi @ericcurtin 

Thank you for your response.

Actually, now it seems to be working!

Closing the issue, I'll open it again if I detect any anomaly.

Have a nice day!
