### ISSUE TITLE
Missing `char*` cast for pointer arithmetic in `inotifytools_next_events`

### ISSUE THREAD

**Issue by hhsdev** [inotify-tools/inotify-tools#165]
In [inotifytools.c:1513](https://github.com/inotify-tools/inotify-tools/blob/4b72dcd15299e1d0cb096397d9aab513ffed1657/libinotifytools/src/inotifytools.c#L1513) we have:

```c
this_bytes = read(inotify_fd, &event[0] + bytes,
```
Pointer arithmetic will cause `&event[0] + bytes` to end up at `(sizeof inotify_event) * bytes` bytes beyond the start of `event`, instead of `bytes` bytes beyond `event`. Can be fixed by having `(char*)&event[0] + bytes` instead.

**Comment by ericcurtin** [comment]
Thanks for reporting, that's a 13+ year old bug you found :) Pushed as 0c54f5b9a5a2b8c7abf1ba9c62fa9fb806261c54
