### ISSUE TITLE
Buildpack available?

### ISSUE THREAD

**Issue by jwright** [inotify-tools/inotify-tools#166]
👋 Thank you for this!

I am trying to use the [pardall markdown](alfredbaudisch/pardall_markdown) in my Elixir application. This package requires that inotify-tools be installed.

I need to get this installed on the [Gigalixir](https://gigalixir.com/) deployment. Gigalixir uses buildpacks like Heroku. Are you aware of any buildpacks that support inotify-tools that are available already?

**Comment by ericcurtin** [comment]
I'll be honest I don't even know what a buildpack is, but if someone contributes one great!
