### ISSUE TITLE
library declares the stack as executable

### ISSUE THREAD

**Issue by eribertomota** [inotify-tools/inotify-tools#169]
Hi @ericcurtin,

Thanks for your work. I am the maintainer of the inotify-tools on Debian.

Debian warns about library in inotify-tools is declaring the stack as executable[1].

[1] https://udd.debian.org/lintian/?packages=inotify-tools

From the lintian system[2]:

> The listed shared library declares the stack as executable.
> 
> Executable stack is usually an error as it is only needed if the code contains GCC trampolines or similar constructs which uses code on the stack. One possible source for false positives are object files built from assembler files which don't define a proper .note.GNU-stack section.
> 
> To see the permissions on the stack, run readelf -l on the shared library and look for the program header of type GNU_STACK. In the flag column, there should not be an E flag set.

[2] https://lintian.debian.org/tags/executable-stack-in-shared-library

Running 'readelf -l libinotifytools.so.0' I can see:

```
Elf file type is DYN (Shared object file)
Entry point 0x0
There are 9 program headers, starting at offset 64

Program Headers:
  Type           Offset             VirtAddr           PhysAddr
                 FileSiz            MemSiz              Flags  Align
[...]
  GNU_STACK      0x0000000000000000 0x0000000000000000 0x0000000000000000
                 0x0000000000000000 0x0000000000000000  RW     0x10
```

Thanks for your attention.

Eriberto

**Comment by ericcurtin** [comment]
I won't have the bandwidth to look at this in detail anytime soon, admittedly I'm spinning too many plates, but if someone pinpoints the lines of code at fault, I would glady help them come to a conclusion.
