### ISSUE TITLE
Failed to decode directory fid

### ISSUE THREAD

**Issue by mirfatif** [inotify-tools/inotify-tools#171]
When watching rootfs (`ext4`), [`open_by_handle_at()`](https://github.com/inotify-tools/inotify-tools/blob/3.22.1.0/libinotifytools/src/inotifytools.c#L775) sometimes fail with `ENOMEM` (ignoring the expected failures with `ESTALE`). Can this be fixed?

Running:
```
fsnotifywatch -e modify,attrib,move,create,delete -F -S /
```
with `inotify-tools 3.22.1.0` on Linux kernel `5.18.6`, Ubuntu `22.04`.

**Comment by ericcurtin** [comment]
@mirfatif certainly open to suggested solutions and contributions.

**Comment by mirfatif** [comment]
Retrying `open_by_handle_at()` on failure seems to work for me, though not a solution. I'm not sure why `ENOMEM` comes when there are GB's of available RAM.

Please reopen this if needed.
