### ISSUE TITLE
--fromfile cannot exclude files?

### ISSUE THREAD

**Issue by qqliuxiaoran** [inotify-tools/inotify-tools#175]
hello @ericcurtin,
I encountered a problem in the process of using inotifywait. I hope you can answer it. Thank you.
My simple --fromfile file locate at `/root/fromfile.txt` as follow:
```
/root/test
@/root/test/1.txt          <----- file
```
My command as follow:
`inotifywait --fromfile /root/fromfile.txt -rmq -e create,modify,close_write,delete,attrib,move /root/test`
When exec `touch /root/test/1.txt` inotifywait still print event.
```
/root/test/ CREATE 1.txt
/root/test/ ATTRIB 1.txt
/root/test/ CLOSE_WRITE,CLOSE 1.txt
```
Inotifywait version is `3.20.11.0`, is this normal behavior? Can you tell me more about the --fromfile feature? Thank you!

**Comment by qqliuxiaoran** [comment]
use linux wildcard...

**Comment by ericcurtin** [comment]
Glad you found a solution quickly, could you tell me more about how Linux wildcard solved your problem?

**Comment by qqliuxiaoran** [comment]
https://download.samba.org/pub/rsync/rsync.1#FILTER_RULES  
I use rsync and inotifywait together to ensure the high availability of my service files. After referring to the filter rules of rsync, I think it is more convenient and can meet my needs. Fortunately, its *, * *,?, [] is very close to the linux wildcard, so i will not use --fromfile or --exclude(command is too long because I have many rules...) feature of inotifywait but use the linux wildcard instead.
just like:
```
rule=/root/test/*.log
[[ $path = $rule ]]
```
