### ISSUE TITLE
inotifywait times out immediately

### ISSUE THREAD

**Issue by suhasbk09** [inotify-tools/inotify-tools#177]
**Describe the bug**

I've been using inotifywait to watch directories on SLES15 SP3. When I launch inotifywait (even with the -r flag), it says "Watches established" and then exits with exit code 2 without reporting an event.

**To Reproduce**

From command line, run inotifywait -r -e close_write /home/suhas/testdir
Observe that after setting up watches, the process immediately exits:
Setting up watches.  Beware: since -r was given, this may take a while! Watches established.
Check the exit code with echo $?
Observe response of 2.
Expected behavior
Inotifywait should wait indefinitely for an event.

**Desktop (please complete the following information):**

OS: SLES15 SP3
Version: 3.14 (via suse repository)
Additional context
This behavior was not happening until today. I just tried restarting the service but that didn't make a difference.

**Comment by suhasbk09** [comment]
@ericcurtin

**Comment by ericcurtin** [comment]
Could you dump a tarball of the contents of /home/suhas/testdir or something like that? What is the filesystem here? What is the inotifytools version?

**Comment by suhasbk09** [comment]
Different filesystems here since multiple partitions. **devtmpfs, btrfs, vfat, tmpfs**   
**Inotify-tools version:** inotify-tools-3.14-bp153.1.17.x86_64
the directory is empty, I touch a dummy file to see if the event gets generated while the watch is set on the dir!

**Comment by ericcurtin** [comment]
Well version 3.14 of inotify-tools is at least 6 years old, before I was a maintainer. Building and trying with the latest commit here would be a start.

I would certainly open a ticket with SUSE or poke the SUSE package maintainer to update their package.

**Comment by suhasbk09** [comment]
Thanks @ericcurtin, will open a ticket with SUSE.
