### ISSUE TITLE
[OpenBSD] Couldn't watch /home/app: Too many open files

### ISSUE THREAD

**Issue by joyboy67** [inotify-tools/inotify-tools#182]
Hello, I'm using Phoenix Framework 1.7.6 with Inotify 3.14 on OpenBSD 7.3

I get this message `Couldn't watch /home/app: Too many open files` after lanch a Phoenix server `mix phx.server`

**Comment by ericcurtin** [comment]
This normally means what it says on the tin, you've hit some limit, you can probably increase that limit, but being honest, I've never booted an OpenBSD OS before.

**Comment by joyboy67** [comment]
> This normally means what it says on the tin, you've hit some limit, you can probably increase that limit, but being honest, I've never booted an OpenBSD OS before.

The "Too many open files" means the files inside the app folder ? Because I tried with a fresh new app (2974 elements) and it's working

**Comment by ericcurtin** [comment]
Could be in the whole OS or process, I would start looking into these limits:

`https://man.openbsd.org/getrlimit.2`

This is actually pretty common if you want to do a recursive watch of files in a directory, if the directory has enough files or another process has a lot of files open already, you can easily hit this limit. It's not really the role of inotify-tools to set this limit, or at least it's not a feature as of today.

**Comment by joyboy67** [comment]
I will try this solution for see https://bytesandbones.wordpress.com/2018/07/27/openbsd-too-many-open-files/

**Comment by ericcurtin** [comment]
Yup that sounds right, very similar to how you'd fix on Linux

**Comment by ericcurtin** [comment]
Closing for now, feel free to reopen if needs be
