### ISSUE TITLE
Can't produce NUL-delimited output

### ISSUE THREAD

**Issue by ormaaj** [inotify-tools/inotify-tools#20]
The `--format` and `--timefmt` options don't appear to interpret `\0` or similar. This severely limits the usefulness of this tool in applications that require safely reading arbitrarily named files.

**Comment by charles-dyfis-net** [comment]
One would expect:

    inotifywait --format '%f\0%w\0'

...to emit two names for each event, with NUL bytes between them, just as `printf '%s\0%s\0' foo bar` emits two NUL-separated strings.

**Comment by charles-dyfis-net** [comment]
@rvoicilas -- would a further example, ie. demonstrating an injection attack based on this behavior, be helpful? See for instance https://www.reddit.com/r/coding/comments/2b7npr/how_to_use_inotifytools_to_trigger_scripts_on/

**Comment by shodanshok** [comment]
I really second this request. I'm using inotifywait for a replication project and using NULL chars as separator would prevent insidious injection-based attack (using specially-crafted file names).

**Comment by nfnty** [comment]
Any progess on this issue?

**Comment by charles-dyfis-net** [comment]
I've started a rough draft of an implementation at dcf419e7c265848f570c3e5a56bfc01d1ad037c1.

Right now it's only an updated `inotifytools_snprintf` -- the other functions in the chain will need to be modified to print the output buffer by length rather than terminating at the first NUL -- and it's completely untested and doubtless buggy.

Will update here as progress continues.

**Comment by ormaaj** [comment]
Every time I feel motivated to fix this myself I realize the whole tool needs to be rewritten. Given the availability of high-quality cross-platform libraries for file-system events, there's really no reason for `inotify-tools` to exist aside from lack of a better option.

**Comment by 813gan** [comment]
I began fixing this in https://github.com/813gan/inotify-tools/tree/NULL-in-format-string
Now touching files `test` and `te\nst2` gives following results:
```
inotifywait -e 'OPEN' -mr --format '%w%f%0' ./ | while IFS= read -r -d '' name ; do
> echo BEGIN
> echo "$name"
> echo END
> done
Setting up watches.  Beware: since -r was given, this may take a while!
Watches established.
BEGIN
./test
END
BEGIN
./te
st2
END
```
Code reviews are highly expected, i dont want to begin my career with CVE :P

**Comment by jrwwallis** [comment]
Is this [workaround](https://unix.stackexchange.com/questions/442035/potential-workaround-to-inotifywait-cant-produce-nul-delimited-output) water-tight?

**Comment by 813gan** [comment]
@jrwwallis  My fork supports NUL-delimited output.

**Comment by leagris** [comment]
Or use C-style string witch is supported at least in Bash and most modern shells.
`--timefmt='%s' --format=$'%T\0% e\0%w%f'`

**Comment by ormaaj** [comment]
@leagris It isn't possible to pass arguments containing a literal `\0` through `ARGV` as they are null-terminated C strings, as are ordinary string arguments handled internally by the shell. The word will be truncated.

```
 $ xxd <<<$'xxx\0xxx'
00000000: 7878 780a                                xxx.
```
