### ISSUE TITLE
Looking for EOS/EOL/EOM date 

### ISSUE THREAD

**Issue by akrattan** [inotify-tools/inotify-tools#203]
Hello Team,

I am looking for Inotify-tools versions EOS/EOL/EOM date for version "3.22.1.0".

Regards,
Abhishek

**Comment by ericcurtin** [comment]
All our releases are here:

**Comment by akrattan** [comment]
I am looking for Inotify-tools version EoS/EoM/EoL
EoS--> end of support
EoL--> End of life
EoM--> End of maintenance

**Comment by ericcurtin** [comment]
I think maybe you should talk to your package maintainer, we don't do backports upstream...
