### ISSUE TITLE
Steps to use the tool in my C++ code

### ISSUE THREAD

**Issue by chengm349** [inotify-tools/inotify-tools#204]
- what's the minimum folders I need to copy the pkg into my building env? seems to me inotifytools folder and libinotifytools.so.0.4.1 for runtime?
- If I don't want to follow example.cpp while loop to have a dedicated thread to monitor,  how to use select() for example to let my thread to monitor other things also?

**Comment by ericcurtin** [comment]
You need to install the headers. How did you install inotify-tools library, via a package or `make install`?

**Comment by chengm349** [comment]
I downloaded the src from here and ran rh_build.sh.

Since I don't have root privilege, I can't run make install. I also don't want to bcos I may build my program on different platforms. So I need to carry the needed headers and lib with my pkg.

**Comment by ericcurtin** [comment]
I think if you `make install` into an alternate directory it should work like:

`make DESTDIR=$HOME/somedir/ install`

**Comment by ericcurtin** [comment]
You can just manually copy the headers into a directory and use your compilers -I option to include that certain directory... None of this stuff strictly requires root (although having root is generally more convenient).

**Comment by chengm349** [comment]
2 tips work.

**Comment by chengm349** [comment]
command "make DESTDIR=$HOME/somedir/ install"
installs libinotifytools.la  libinotifytools.so  libinotifytools.so.0  libinotifytools.so.0.4.1
So should my program link to libinotifytools.la during compilation?

**Comment by ericcurtin** [comment]
https://stackoverflow.com/questions/12237282/whats-the-difference-between-so-la-and-a-library-files
