### ISSUE TITLE
inotifytools_wd_from_filename (char const *filename)

### ISSUE THREAD

**Issue by chengm349** [inotify-tools/inotify-tools#205]
assume I called inotifytools_watch_recursively() with my top folder. If I call fd = inotifytools_wd_from_filename (char const *filename) and filename is my top folder name. May I assume that any event happens under top folder will get select(fd) being triggered?

**Comment by chengm349** [comment]
I modified example.cpp (attached) and seems inotifytools_wd_from_filename(".") does not work because fd always -1.

**Comment by chengm349** [comment]
keen to receive further advice.

**Comment by chengm349** [comment]
If I can use select() to monitor a watch descriptor, that will be very useful. Hope my modified example.cpp test code missed something.

**Comment by chengm349** [comment]
I'll modify the code.

**Comment by chengm349** [comment]
I'll modify the code.

**Comment by ericcurtin** [comment]
Please feel free to contribute back changes.

**Comment by chengm349** [comment]
Here is my change to inotifytools.cpp (**Bold** part).

int inotifytools_init(int fanotify, int watch_filesystem, int verbose) {
        if (initialized)
                return **initialized**;

        error = 0;
        verbosity = verbose;
        // Try to initialise inotify/fanotify
        if (fanotify) {
#ifdef LINUX_FANOTIFY
self_pid = getpid();
                fanotify_mode = 1;
                fanotify_mark_type =
                    watch_filesystem ? FAN_MARK_FILESYSTEM : FAN_MARK_INODE;
                inotify_fd =
                    fanotify_init(FAN_REPORT_FID | FAN_REPORT_DFID_NAME, 0);
#endif
        } else {
                fanotify_mode = 0;
                inotify_fd = inotify_init();
        }
        if (inotify_fd < 0) {
                error = errno;
                return 0;
        }

        collect_stats = 0;
        initialized = **notify_fd**;
        tree_wd = rbinit(wd_compare, 0);
        tree_fid = rbinit(fid_compare, 0);
        tree_filename = rbinit(filename_compare, 0);
        timefmt.clear();

        return **initialized**;
}

**Comment by ericcurtin** [comment]
Could you open a PR @chengm349 so others can benefit from this example?

**Comment by chengm349** [comment]
Please elaborate further. What's PR? How to do it. thanks.
