### ISSUE TITLE
Memory leak when removing a watched directory

### ISSUE THREAD

**Issue by mbrimer** [inotify-tools/inotify-tools#29]
Hi,

I'm using inotify-tools to watch a directory tree over a long period of time where sub-directories are added and removed. When my application code receives a directory removal event (IN_DELETE.IN_ISDIR) I call inotifytools_remove_watch_by_filename to destroy the watch. However there appears to be a race condition between inotifytools and the kernel because sometimes this will succeed and other times the internal remove_inotify_watch function receives -1 from its call to inotify_rm_watch with errno set to EINVAL. However I think this is what the kernel should report if the directory has already been deleted. In this scenario, the inotifytools tree nodes are not destroyed and the number of watches remains unaltered. Over a period of time this results in the number of watches growing unintentionally. Same behaviour experienced with inotifytools_remove_watch_by_wd as it is also using the remove_inotify_watch function.

It seems to me that inotifytools should either deal with these cases silently or there should be a way for an application to distinguish between the two cases:
1. Remove a watch without the directory having been deleted (currently supported).
2. Destroy an inotifytools watch in reaction to a directory deletion event.

I tried silently absorbing the EINVAL and that fixed my problem but isn't a long term solution as it's not appropriate for case 1 above.

Does this make sense?
Please let me know if you need further information or explanation.

Thanks,
Mike.

**Comment by cg666** [comment]
Hi Mike,

I faced the same issue :

- I monitor a folder with inotifytools_watch_recursively()
- I create a folder foo/ and monitor it
- I create a folder foo/bar/ and monitor it
- I delete foo/

I get the error when calling inotifytools_remove_watch_by_wd() and I see leak inotifytools_get_num_watches(). I workaround the issue by deleting stuffs manualy (rbdelete and destroy_watch)

I suggest the following changes :

`

int inotifytools_remove_watch_by_wd( int wd ) {
	watch *w;
	int    result;

	result = 1;
	niceassert( init, "inotifytools_initialize not called yet" );

	w = watch_from_wd(wd);

	if (w)
	{
		if (!remove_inotify_watch(w))
		{
			result = 0;
		}

		if (result)
		{
			rbdelete(w, tree_wd);
			rbdelete(w, tree_filename);
			destroy_watch(w);
		}
	}
	return result;
}
`

**Comment by cg666** [comment]
Hi Mike,

I faced the memory leak, I use a script to create dummy folders :

1. I monitor a folder called "test/", the program add watches on each created sub folders
1. X = 1
1. Create the following folders : test/fooX/barX/fooX/
1. Delete test/fooX/
1. I increment X
1. If X < 1000 Goto step 3 else stop

At the end, inotifytools_get_num_watches() returns 3001. That's not expected ?

Anyway, regarding EINVAL comment, I suggest the following changes :

```
int inotifytools_remove_watch_by_wd( int wd ) {
	watch *w;
	int    result;

	result = 1;
	niceassert( init, "inotifytools_initialize not called yet" );

	w = watch_from_wd(wd);

	if (w)
	{
		if (!remove_inotify_watch(w))
		{
			result = 0;
		}
		// Whatever the result we delete it.
		// In case of failure, it's an EINVAL from inotify_rm_watch() 
		// From the manual, it means the File descriptor is no more valid.
		// No need to keep it.
		rbdelete(w, tree_wd);
		rbdelete(w, tree_filename);
		destroy_watch(w);
	}
	return result;
}
```

Hope this help.

Best regards

**Comment by bzl9** [comment]
> Hi Mike,
> 
> I faced the memory leak, I use a script to create dummy folders :
> 
> 1. I monitor a folder called "test/", the program add watches on each created sub folders
> 2. X = 1
> 3. Create the following folders : test/fooX/barX/fooX/
> 4. Delete test/fooX/
> 5. I increment X
> 6. If X < 1000 Goto step 3 else stop
> 
> At the end, inotifytools_get_num_watches() returns 3001. That's not expected ?
> 
> Anyway, regarding EINVAL comment, I suggest the following changes :
> 
> ```
> int inotifytools_remove_watch_by_wd( int wd ) {
> 	watch *w;
> 	int    result;
> 
> 	result = 1;
> 	niceassert( init, "inotifytools_initialize not called yet" );
> 
> 	w = watch_from_wd(wd);
> 
> 	if (w)
> 	{
> 		if (!remove_inotify_watch(w))
> 		{
> 			result = 0;
> 		}
> 		// Whatever the result we delete it.
> 		// In case of failure, it's an EINVAL from inotify_rm_watch() 
> 		// From the manual, it means the File descriptor is no more valid.
> 		// No need to keep it.
> 		rbdelete(w, tree_wd);
> 		rbdelete(w, tree_filename);
> 		destroy_watch(w);
> 	}
> 	return result;
> }
> ```
> 
> Hope this help.
> 
> Best regards

I have changed my inotify-tools code like what you write above, but the memleak still ex
> 
> I faced the memory leak, I use a script to create dummy folders :
> 
> 1. I monitor a folder called "test/", the program add watches on each created sub folders
> 2. X = 1
> 3. Create the following folders : test/fooX/barX/fooX/
> 4. Delete test/fooX/
> 5. I increment X
> 6. If X < 1000 Goto step 3 else stop
> 
> At the end, inotifytools_get_num_watches() returns 3001. That's not expected ?
> 
> Anyway, regarding EINVAL comment, I suggest the following changes :
> 
> ```
> int inotifytools_remove_watch_by_wd( int wd ) {
> 	watch *w;
> 	int    result;
> 
> 	result = 1;
> 	niceassert( init, "inotifytools_initialize not called yet" );
> 
> 	w = watch_from_wd(wd);
> 
> 	if (w)
> 	{
> 		if (!remove_inotify_watch(w))
> 		{
> 			result = 0;
> 		}
> 		// Whatever the result we delete it.
> 		// In case of failure, it's an EINVAL from inotify_rm_watch() 
> 		// From the manual, it means the File descriptor is no more valid.
> 		// No need to keep it.
> 		rbdelete(w, tree_wd);
> 		rbdelete(w, tree_filename);
> 		destroy_watch(w);
> 	}
> 	return result;
> }
> ```
> 
> Hope this help.
> 
> Best regards

I have changed my inotify-tools code like what you write above, but the memleak still exists.  
Could you give me some other suggestions？

Thanks

**Comment by bzl9** [comment]
> Hi Mike,
> 
> I faced the memory leak, I use a script to create dummy folders :
> 
> 1. I monitor a folder called "test/", the program add watches on each created sub folders
> 2. X = 1
> 3. Create the following folders : test/fooX/barX/fooX/
> 4. Delete test/fooX/
> 5. I increment X
> 6. If X < 1000 Goto step 3 else stop
> 
> At the end, inotifytools_get_num_watches() returns 3001. That's not expected ?
> 
> Anyway, regarding EINVAL comment, I suggest the following changes :
> 
> ```
> int inotifytools_remove_watch_by_wd( int wd ) {
> 	watch *w;
> 	int    result;
> 
> 	result = 1;
> 	niceassert( init, "inotifytools_initialize not called yet" );
> 
> 	w = watch_from_wd(wd);
> 
> 	if (w)
> 	{
> 		if (!remove_inotify_watch(w))
> 		{
> 			result = 0;
> 		}
> 		// Whatever the result we delete it.
> 		// In case of failure, it's an EINVAL from inotify_rm_watch() 
> 		// From the manual, it means the File descriptor is no more valid.
> 		// No need to keep it.
> 		rbdelete(w, tree_wd);
> 		rbdelete(w, tree_filename);
> 		destroy_watch(w);
> 	}
> 	return result;
> }
> ```
> 
> Hope this help.
> 
> Best regards

I have changed my inotify-tools code like what you write above, but the memleak still exists.
Could you give me some other suggestions？

Thanks
