### ISSUE TITLE
Package release status

### ISSUE THREAD

**Issue by crodjer** [inotify-tools/inotify-tools#39]
I noticed that the last release for inotify-tools was [v3.14](https://github.com/rvoicilas/inotify-tools/tree/v3.14). After that there have been over 2 years worth of changes which are yet to be released.

Are there any plans to release inotify-tools in the near future? The current version I have from the distribution I use (ArchLinux) is also (v3.14). Have there been any blocking changes which break the user interface compatibility?

Specifically speaking: 1c0aa54b87855e8d and 20c90ec89c821fe8 are a couple of changes which are of a specific importance to me for a [utility](https://github.com/crodjer/watchman) I am writing. It is directly based on the `inotifywait` command.

**Comment by flip111** [comment]
Any update on the release? I think the issue is still relevant, perhaps reopen?
