### ISSUE TITLE
Can't build according to INSTALL

### ISSUE THREAD

**Issue by riebling** [inotify-tools/inotify-tools#42]
The build commands seem to have changed with respect to the instructions in INSTALL. For example, there is no 'configure' file. It gets created if you run autogen.sh, but INSTALL instructions should probably mention this.

**Comment by slate0** [comment]
Same goes for the wiki page.

**Comment by excenter** [comment]
what is the current process for compiling? instructions unclear

**Comment by rustam9** [comment]
I believe ./autogen.sh, then ./configure --prefix=/usr && make && su -c 'make install' like the instruction says.
