### ISSUE TITLE
Linux - inotifywait: Removing two or more files/directories at the same time reports only one deletion.

### ISSUE THREAD

**Issue by jiraz2112114** [inotify-tools/inotify-tools#44]
I am monitoring a directory recursively for deletion event. 
As an example, If I am monitoring a directory "test" which has two sub-directories "sub-dir1" and "sub-dir2". Test cases below:

1) rm -rf sub-dir1 reports the deletion event alright.
2) rm -rf sub-dir2 reports the deletion event alright as well.

Problem:

1) rm -rf sub-dir1 sub-dir2 reports deletion of sub-dir1 only, not both.
2) rm -rf sub-dir2 sub-dir1 reports deletion of sub-dir2 only, not both.

**Comment by 813gan** [comment]
I'm unable to reproduce this. inotify-tools-3.20.1, kernel 4.9.94.
