### ISSUE TITLE
Handle MOVED_TO / MOVED_FROM event outside watched folder

### ISSUE THREAD

**Issue by vschoener** [inotify-tools/inotify-tools#45]
Hi,

I'm making a script to sync a folder without the rsync process, 2 locals folders.

Its was not so hard to manage the rest but,  for these events, we don't have the information about the folder location where the file come or go when it's outside the watched folder.

Also when the event occurred inside the watched folder, we have these 2 events triggered 
-> MOVED_FROM followed by MOVED_TO that make things a little more complicated to handle. (store last event to know where the file / directory  is and will go etc etc).

Any idea ? :) Is there an available variable to use with the outside part ?

Thanks

**Comment by hamoid** [comment]
I think https://unix.stackexchange.com/questions/163749/inotifywait-get-old-and-new-file-name-when-renaming shows a way to do it. Issue #43 is about getting this implemented.
