### ISSUE TITLE
Bad form for '-t' option for HP-UX

### ISSUE THREAD

**Issue by zhec9** [inotify-tools/inotify-tools#47]
I'm compiling on HP-UX (ia64-11.31) using ./configure CC="cc -Ae -D_XOPEN_SOURCE=500". When I attempted compiling with gmake, I get this error:
cc: error 1914: bad form for `-t' option

Here's a more detailed report below:
/usr/local/bin/gmake  all-recursive
gmake[1]: Entering directory '/root/inotify-tools'
Making all in libinotifytools
gmake[2]: Entering directory '/root/inotify-tools/libinotifytools'
Making all in src
gmake[3]: Entering directory '/root/inotify-tools/libinotifytools/src'
Making all in inotifytools
gmake[4]: Entering directory '/root/inotify-tools/libinotifytools/src/inotifytools'
/usr/local/bin/gmake  all-am
gmake[5]: Entering directory '/root/inotify-tools/libinotifytools/src/inotifytools'
gmake[5]: Nothing to be done for 'all-am'.
gmake[5]: Leaving directory '/root/inotify-tools/libinotifytools/src/inotifytools'
gmake[4]: Leaving directory '/root/inotify-tools/libinotifytools/src/inotifytools'
gmake[4]: Entering directory '/root/inotify-tools/libinotifytools/src'
source='inotifytools.c' object='inotifytools.lo' libtool=yes \
DEPDIR=.deps depmode=hp2 /bin/sh ../../config/depcomp \
/bin/sh ../../libtool  --tag=CC   --mode=compile cc -Ae -D_XOPEN_SOURCE=500 -DHAVE_CONFIG_H -I. -I../.. -I../../libinotifytools/src/inotifytools    -std=c99 -g -c -o inotifytools.lo inotifytools.c
libtool: compile:  cc -Ae -D_XOPEN_SOURCE=500 -DHAVE_CONFIG_H -I. -I../.. -I../../libinotifytools/src/inotifytools -std=c99 -g -c +Maked inotifytools.c  -DPIC -o .libs/inotifytools.o
cc: error 1914: bad form for `-t' option
Makefile:678: recipe for target 'inotifytools.lo' failed
gmake[4]: **\* [inotifytools.lo] Error 1
gmake[4]: Leaving directory '/root/inotify-tools/libinotifytools/src'
Makefile:740: recipe for target 'all-recursive' failed
gmake[3]: **\* [all-recursive] Error 1
gmake[3]: Leaving directory '/root/inotify-tools/libinotifytools/src'
Makefile:351: recipe for target 'all-recursive' failed
gmake[2]: **\* [all-recursive] Error 1
gmake[2]: Leaving directory '/root/inotify-tools/libinotifytools'
Makefile:403: recipe for target 'all-recursive' failed
gmake[1]: **\* [all-recursive] Error 1
gmake[1]: Leaving directory '/root/inotify-tools'
Makefile:335: recipe for target 'all' failed
gmake: **\* [all] Error 2

**Comment by ericcurtin** [comment]
Closing as unsupported platform.
