### ISSUE TITLE
Please drop "Linux" from your README headline

### ISSUE THREAD

**Issue by yurivict** [inotify-tools/inotify-tools#48]
It builds on FreeBSD, and I am going to submit it as a port.

**Comment by yurivict** [comment]
Port is submitted to FreeBSD.

**Comment by ericcurtin** [comment]
Hi @yurivict,

I made a start on the FreeBSD upstream port. It builds! Would you mind helping me out I don't have any FreeBSD machine around and have never developed on the platform.

https://cirrus-ci.com/github/inotify-tools/inotify-tools

You will see the unit tests fail, maybe the integration tests fail/pass too, I dunno. Once that's complete I'll drop Linux from everywhere and we will have official FreeBSD upstream support. This script will show you how to run the tests:

https://github.com/inotify-tools/inotify-tools/blob/master/build_and_test.sh

**Comment by yurivict** [comment]
@ericcurtin There is already a port for ```inotify-tools```: ```sysutils/inotify-tools```.

**Comment by ericcurtin** [comment]
Yes downstream. Do the unit tests/integration tests pass on this port?

We can leave it as unofficial support if needs be no biggie. I'll probably create a new release in the next few days. I can just stop running the tests on FreeBSD, but keep the code building.

**Comment by yurivict** [comment]
How to run the tests?

**Comment by ericcurtin** [comment]
Steps are in this script above

https://github.com/inotify-tools/inotify-tools/blob/master/build_and_test.sh

There's only a couple of lines to that script

**Comment by ericcurtin** [comment]
@yurivict you will also see here they currently fail:

https://cirrus-ci.com/github/inotify-tools/inotify-tools
