### ISSUE TITLE
Not able to compile inotify on hpux 11.31. ( make issues )

### ISSUE THREAD

**Issue by teja402000** [inotify-tools/inotify-tools#50]
Not able to compile inotify on hpux 11.31.
Getting following error ;

root #/home/tejachau/inotify-tools-3.14 >make
No suffix list.
        make  all-recursive
No suffix list.
Making all in libinotifytools
No suffix list.
Making all in src
Making all in inotifytools
No suffix list.
        make  all-am
No suffix list.
No suffix list.
No suffix list.
No suffix list.
No suffix list.
        /bin/sh ../../libtool --tag=CC    --mode=compile /usr/local/bin/gcc -DHAVE_CONFIG_H -I. -I../.. -I../../libinotifytools/src/inotifytools     -std=c99 -g -O2 -MT inotifytools.lo -MD -MP -MF .deps/inotifytools.Tpo -c -o inotifytools.lo inotifytools.c
libtool: compile:  /usr/local/bin/gcc -DHAVE_CONFIG_H -I. -I../.. -I../../libinotifytools/src/inotifytools -std=c99 -g -O2 -MT inotifytools.lo -MD -MP -MF .deps/inotifytools.Tpo -c inotifytools.c  -fPIC -DPIC -o .libs/inotifytools.o
In file included from inotifytools.c:31:
/usr/include/regex.h:118: error: static or type qualifiers in abstract declarator
In file included from inotifytools/inotify.h:12,
                 from inotifytools.c:34:
inotifytools/inotify-nosys.h: In function 'inotify_init':
inotifytools/inotify-nosys.h:153: warning: implicit declaration of function 'syscall'
inotifytools.c: In function 'inotifytools_cleanup':
inotifytools.c:330: warning: implicit declaration of function 'close'
inotifytools.c: In function 'replace_filename':
inotifytools.c:383: warning: implicit declaration of function 'asprintf'
inotifytools.c: In function 'onestr_to_event':
inotifytools.c:563: warning: implicit declaration of function 'strcasecmp'
inotifytools.c: In function 'inotifytools_set_filename_by_wd':
inotifytools.c:812: warning: implicit declaration of function 'strdup'
inotifytools.c:812: warning: assignment makes pointer from integer without a cast
inotifytools.c: In function 'inotifytools_set_filename_by_filename':
inotifytools.c:834: warning: assignment makes pointer from integer without a cast
inotifytools.c: In function 'create_watch':
inotifytools.c:892: warning: assignment makes pointer from integer without a cast
inotifytools.c: In function 'inotifytools_watch_files':
inotifytools.c:1002: warning: assignment makes pointer from integer without a cast
inotifytools.c: In function 'inotifytools_next_events':
inotifytools.c:1164: warning: type defaults to 'int' in declaration of 'fd_set'
inotifytools.c:1164: warning: type defaults to 'int' in declaration of 'read_fds'
inotifytools.c:1166: error: storage size of 'read_timeout' isn't known
inotifytools.c:1172: warning: implicit declaration of function 'FD_ZERO'
inotifytools.c:1173: warning: implicit declaration of function 'FD_SET'
inotifytools.c:1174: warning: implicit declaration of function 'select'
inotifytools.c:1188: warning: implicit declaration of function 'ioctl'
inotifytools.c:1188: error: 'FIONREAD' undeclared (first use in this function)
inotifytools.c:1188: error: (Each undeclared identifier is reported only once
inotifytools.c:1188: error: for each function it appears in.)
inotifytools.c:1197: warning: implicit declaration of function 'read'
inotifytools.c: In function 'inotifytools_watch_recursively_with_exclude':
inotifytools.c:1288: error: 'DIR' undeclared (first use in this function)
inotifytools.c:1288: error: 'dir' undeclared (first use in this function)
inotifytools.c:1291: warning: implicit declaration of function 'opendir'
inotifytools.c:1294: error: 'ENOTDIR' undeclared (first use in this function)
inotifytools.c:1312: error: storage size of 'my_stat' isn't known
inotifytools.c:1313: warning: implicit declaration of function 'readdir'
inotifytools.c:1313: warning: assignment makes pointer from integer without a cast
inotifytools.c:1316: error: dereferencing pointer to incomplete type
inotifytools.c:1317: error: dereferencing pointer to incomplete type
inotifytools.c:1318: error: dereferencing pointer to incomplete type
inotifytools.c:1319: warning: implicit declaration of function 'lstat64'
inotifytools.c:1322: error: 'EACCES' undeclared (first use in this function)
inotifytools.c:1325: warning: implicit declaration of function 'closedir'
inotifytools.c:1329: warning: implicit declaration of function 'S_ISDIR'
inotifytools.c:1330: warning: implicit declaration of function 'S_ISLNK'
inotifytools.c:1332: error: dereferencing pointer to incomplete type
inotifytools.c:1359: error: 'ENOENT' undeclared (first use in this function)
inotifytools.c:1360: error: 'ELOOP' undeclared (first use in this function)
inotifytools.c:1373: warning: assignment makes pointer from integer without a cast
inotifytools.c: In function 'isdir':
inotifytools.c:1598: error: storage size of 'my_stat' isn't known
inotifytools.c:1601: error: 'ENOENT' undeclared (first use in this function)
inotifytools.c: In function 'inotifytools_snprintf':
inotifytools.c:1826: error: 'struct inotify_event' has no member named 'name'
inotifytools.c:1836: error: 'EINVAL' undeclared (first use in this function)
inotifytools.c:1840: error: 'EMSGSIZE' undeclared (first use in this function)
inotifytools.c: In function 'inotifytools_ignore_events_by_regex':
inotifytools.c:2021: error: 'EINVAL' undeclared (first use in this function)
**\* Error exit code 1

Stop.
**\* Error exit code 1

Stop.
**\* Error exit code 1

Stop.
**\* Error exit code 1

Stop.
**\* Error exit code 1

Stop.

**Comment by ericcurtin** [comment]
We could possibly get this working if HPUX kernel has inotify/kqueue or some other interface/API like this for monitoring files/directories. I'd encourage someone to try. If someone could provide a HPUX build machine we could hook into this repo directly like our Linux x86/aarch64 and FreeBSD builds, otherwise it would be hard to maintain HPUX support in the long term.

Similar to #11, the first steps would be:

- Get code building
- Get unit tests passing
- Get integration tests passing

How to do that is all in this script:

https://github.com/inotify-tools/inotify-tools/blob/master/build_and_test.sh

**Comment by ericcurtin** [comment]
Closing for now, stale issue
