### ISSUE TITLE
inotifywait examples don't work when filenames has space characters

### ISSUE THREAD

**Issue by tkittich** [inotify-tools/inotify-tools#51]
Hello,

The examples should recommend best practices. However, inotifywait examples don't work when filenames has space characters. I am not sure exactly how to correct the bug. But this might work:

```
inotifywait -m -r -e create --format "%e%w%f" /some/folders |
while read output; do
  case "$output" in
    CREATE,ISDIR*)
      fullpath=${output#CREATE,ISDIR}
      echo "$0: $fullpath"
      ;;
  esac
done
```

**Comment by luku** [comment]
I struggled with this as well, and this works fine for me:
```bash
inotifywait -m -r -e moved_to -e close_write --format "%e %w%f" /some/folders |
  while read evt dir file; do
    echo "Event: $evt, Dir: $dir, File: $file"
    echo "Fullpath: $dir $file" #note the space between $dir and $file
done
```
`Event` is safe, `dir` will pick everything until first space and `file` gets rest. Of course, both `dir` and `file` variables are wrong, but in most cases the most important piece is anyway the absolute path to file/dir that was changed. One problem is that if you get dir+file without any spaces, the final `$path` contains trailing whitespace, so if you care, trim them with: `path=$(echo "$dir $file" | sed -e 's/[[:space:]]*$//')`
Also I'm watching different events than @tkittich, so not sure if this always works, so I would happy if there are more tests (mine is Ubuntu 14.04 and script runs `#!/bin/bash`)

**Comment by sebastian-inman-design** [comment]
@luku For anyone else trying this and getting the wrong output, your inotifywait --format should have a space between the %w and %f, looking like this:

`inotifywait -m -r -e moved_to -e close_write --format "%e %w %f" /some/folders |
  while read evt dir file; do
    echo "Event: $evt, Dir: $dir, File: $file"
    echo "Fullpath: $dir $file" #note the space between $dir and $file
done`

**Comment by luku** [comment]
@sebastian-inman-design Your solution doesn't work. Example dir: `/home/ubuntu/dir with space`. Example file: `file with space.txt`. If you start your monitoring script and call `touch /home/ubuntu/dir\ with\ space/file\ with\ space.txt` the output is: **Fullpath: /vagrant/test/dir with space/ file with space.txt** See the additional space before filename?

**Comment by rvoicilas** [comment]
Guys, I think we're looking at this from the wrong perspective - my opinion is that `inotifywait` works as expected, I think it is `read`'s fault combined with the `--format` you are trying to use. 
If instead you use other delimiter than space (say comma) you will see that the output of `inotifywait` is the correct one:
```sh
inotifywait ... --format "%e,%w,%f" <folders with spaces in name> |
perl -F, -lane 'print "Event: *$F[0]*, Dir: *$F[1]*, File: *$F[2]*"'
```
will print the correct dir name and file name even if one or both of those have spaces in their name (stars added in there for visual)

Even if you don't pipe the output to perl, awk, bash and change the format delimiter you will see that the components of the format are as expected.

Let me know otherwise if I don't understand the issue at hand.

**Comment by tkittich** [comment]
Thank you for the reply. The problem is not specific to inotifywait and has to do with how to properly parse the output format. If I remember correctly, it's not possible to universally know where %w ends and where %f begins without using special characters. But using special characters would also don't work with files with special characters as the filenames. So, format with %w%f together as the fullpath should work.

**Comment by luku** [comment]
I can confirm what @tkittich suggested works perfect, thanks! In all frustration I missed the possibility to catch both `%w` and `%f` inside single variable `fullpath`. By doing that, there is no trailing whitespace. So unless there will be someday event that contains spaces, this is the way to go.

Also I tested running inotify only like this: `inotifywait -m -r --format "%e,%w,%f" /tmp/dir\ with\ spaces` and the output is correct (even `%w` and `%f`) as @rvoicilas said. 
Strange to see that I didn't understand this already one and half year ago...

**Comment by kocane** [comment]
@tkittich thank you soooo much

**Comment by t-deux** [comment]
Indeed the concern comes from the "read" command in the "while" loop. It takes the space as the separator by default.

Workaround of the problem :
1. Define a separator that you should not find in your file and folder names for the inotifywait command.
   I use this one "<@@>". As it is made up of several characters, it cannot be directly interpreted by the “read” command, even by specifying "IFS='<@@>'" as a separator. IFS information with the "read" command only supports separators with one character.
   Exemple : 
   inotifywait -m -r -e create -e moved_to -e close_write --format "%e<@@>%w<@@>%f" /folder1/folder2 |

2. Modifying the default separator for the "read" command by "IFS=$'\n'" which corresponds to the end of line.
   Exemple :
   while IFS=$'\n' read line

3. Then use awk to retrieve the information in the $action, $path, and $file variables when processing the while loop.
   Exemple :
   while IFS=$'\n' read line
   do
    action=$(echo $line | awk -F '<@@>' {'print $1'})
    path=$(echo $line | awk -F '<@@>' {'print $2'})
    file=$(echo $line | awk -F '<@@>' {'print $3'})
    <Your code>
   done

It works fine for me.
