### ISSUE TITLE
exclude from file

### ISSUE THREAD

**Issue by brewster1134** [inotify-tools/inotify-tools#67]
As of version 3.4 (according to the changelog), _"The list of files to watch or exclude can now be read in from a file"_

Is the documentation to exclude from a file missing? `--fromfile` covers the file of paths to watch, but what is the option for pointing to the list of paths to exclude?

**Comment by mrspuratic** [comment]
Perhaps your distro isn't up to date, the v3.14 man page documents this:
```     
--fromfile <file>
              Read filenames to watch or exclude from a file, one filename per
              line.  If filenames begin with @ they are excluded as  described
              above.   If  <file>  is  `-',  filenames  are read from standard
              input.  Use this option if you need to watch too many  files  to
              pass in as command line arguments.
```

**Comment by sumeshprabhu86** [comment]
IS there any similar option using which we can add excludes as well by writing to a file and not passing the argument --exclude ?

**Comment by brewster1134** [comment]
i have not had a chance to try the above mentioned syntax, but it was documentation i had not seen, but described exactly my use case
