### ISSUE TITLE
Is this project still maintained?

### ISSUE THREAD

**Issue by q2dg** [inotify-tools/inotify-tools#68]
Last closed issues and merged PR are from 2014...so I'd like to know the status of this tool.
Thanks

**Comment by aggsol** [comment]
I think we might need a fork

**Comment by eMPee584** [comment]
> we might need a fork

uhhm.. there already seem to be about 20 🤣

**Comment by rvoicilas** [comment]
Uhm, it hasn't been maintained for the last 4 years or so - not sure if I'll have time starting from now on to do so, but I'm planning on giving a try, at least to close some of the existing issues and PRs. Also, I just released [3.20.0](https://github.com/rvoicilas/inotify-tools/tree/3.20.0) if this helps you.

**Comment by 813gan** [comment]
@rvoicilas maybe You should give someone write access?

**Comment by jmagnusson** [comment]
@rvoicilas Any chance we might see 3.20.1 in OS package managers? Most seem to be stuck at 3.14

**Comment by cyc1ingsir** [comment]
@rvoicilas There have been a couple of commits since the last release 3.20.1.
Any chance, you could make a release 3.20.2 including these commits?
Including at least the PR #104  in the new release would be very welcome!

This would be really helpful to get a PR reviewed, providing a SynoCommunity package for this tools.
Thank you very much in advance

**Comment by ericcurtin** [comment]
@rvoicilas we need someone to have write access or someone to start maintaining a fork, the former would be preferable so you could still be involved. Nothing has been merged in 2 years! I wanted to open a PR myself, but I wonder is it worth the effort if it's gonna stay in limbo.

**Comment by ericcurtin** [comment]
@q2dg @aggsol @eMPee584 @rvoicilas @813gan @jmagnusson @cyc1ingsir @carlbordum @angerangel @bmwiedemann @itpflop @chipitsine @DabeDotCom @EdwardBetts @guilhermepiccoli @jackiehjm @yurivict @laindir @toconnor @ghost

I'm happy enough to maintain this as a fork if you'd like to open pull requests, issues, etc. here?

https://github.com/ericcurtin/inotify-tools

**Comment by 813gan** [comment]
Hi @ericcurtin.
I very happy to see that someone cares about this pretty important project.
My PR needs some work but when i will clean up things i will open it for your fork.

Did you contact with package maintainers? I bet most of distros should switch to some fork as @rvoicilas seems to be dead...

**Comment by bmwiedemann** [comment]
Somehow I can open PRs to a hundred forks, but not yours. Feel free to `git am` my https://github.com/rvoicilas/inotify-tools/pull/97.patch

**Comment by carlbordum** [comment]
@ericcurtin, thanks for doing this.

@bmwiedemann I experienced the same thing, some bug with GitHub. Try using the GUI starting from this link https://github.com/ericcurtin/inotify-tools/compare/master...carlbordum:master, then it worked for me.

**Comment by cyc1ingsir** [comment]
Nice move.
Maybe you could have a brief look over the PRs in this project.
#104 looks urgent to me.
A new release would be great too.

**Comment by rvoicilas** [comment]
> @q2dg @aggsol @eMPee584 @rvoicilas @813gan @jmagnusson @cyc1ingsir @carlbordum @angerangel @bmwiedemann @itpflop @chipitsine @DabeDotCom @EdwardBetts @guilhermepiccoli @jackiehjm @yurivict @laindir @toconnor @ghost
> 
> I'm happy enough to maintain this as a fork if you'd like to open pull requests, issues, etc. here?
> 
> https://github.com/ericcurtin/inotify-tools

@ericcurtin Thank you for taking the time to get involved in this project. Unfortunately, my time has been limited over the last couple of years. I'm more than willing to help with the transition - I can add you as a collaborator to this project which presumably should you give you write access or I can point the current `README` to your fork of the project - whatever works best for you.

**Comment by ericcurtin** [comment]
Thanks for the quick response @rvoicilas! Could you add me as a collaborator to this project? And I can look at all the pull requests issues here, rather than asking everyone to re-open everything.

And then you can get involved if your time frees up again :)

It would save me rewriting all urls etc. I'd rather close the fork if possible.

**Comment by ericcurtin** [comment]
Hi @rvoicilas I see I now have push access. Thanks for that! I can now merge some PRs :)

There are still many things I cannot do, such as edit the outdated url in the project description.

I created a https://github.com/orgs/inotify-tools organization so this project can have multiple owners with full access.

Could you accept that invite? Then I can set you as an owner and we can have multiple admins.

**Comment by rvoicilas** [comment]
@ericcurtin Done! Thank you!

**Comment by ericcurtin** [comment]
I just gave you "Owner" access on that organization. The last step is to transfer this repo to that organization, in this repos settings:

![image](https://user-images.githubusercontent.com/1694275/73262291-bd638480-41c5-11ea-8df4-fe1a4944caff.png)

It just enables us to have multiple owners, if that's ok with you?

**Comment by ericcurtin** [comment]
We now have two maintainers to avoid single points of failure.

**Comment by ericcurtin** [comment]
@cyc1ingsir #104 was merged I'll create a new release in the coming days

@813gan haven't looked at your PR. It's bloody huge! If it breaks backwards compatibility we may not be able to merge.

**Comment by carlbordum** [comment]
@ericcurtin again, thanks for doing this.

If you're fine with it, I would like to volunteer as well and help you with some of the open issues and prs. Also then, new issues are unlikely to go unanswered.

**Comment by bmwiedemann** [comment]
When I see things like #109 I'm not so sure anymore... It is always a good thing to have others review code to reduce the likelyhood of introducing errors.

**Comment by bmwiedemann** [comment]
@ericcurtin I'd really prefer, if you could follow best practices of developing open source software:

* you should **not** force push to master (it is only OK to do with a devel / feature branch)
* write [good commit messages](https://chris.beams.io/posts/git-commit/)
* do not mix in unrelated changes into commits - makes them easier to understand
* ask people for code reviews (with over 200 forks there seem to be some people who are familiar with the codebase) - I code for 25+ years and still find reviews very valuable.
* reference issue IDs in commits/PRs as `Fixes #xxx` to get automatic cross-links in github

Thank you.
