### ISSUE TITLE
error while loading shared libraries: libinotifytools.so.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by HardlyMirage** [inotify-tools/inotify-tools#7]
I installed on Centos 5.5 from source. I believe the libinotifytools library is not linked correctly. How can I fix this?

**Comment by harole** [comment]
resolution：
1. 32 bit：ln -s /usr/local/lib/libinotifytools.so.0 /usr/lib/libinotifytools.so.0
2. 64 bit：ln -s /usr/local/lib/libinotifytools.so.0 /usr/lib64/libinotifytools.so.0

**Comment by spillkiss** [comment]
For when `./configure --prefix=/usr --libdir=/lib64` doesn't correct the issue,
and `ldconfig -v -l /usr/lib64/libinotifytools.so.0.4.1` is of no avail,
and `ln -s /usr/local/lib/libinotifytools.so.0 /usr/lib64/libinotifytools.so.0` may not work ...

you may be able to problem-solve the application startup with:
```
strace -f -s 3000 inotifywait
...
stat("/usr/lib/x86_64", 0x7ffe64daf550) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/lib/libinotifytools.so.0", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
stat("/usr/lib", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
writev(2, [{iov_base="inotifywait", iov_len=11}, {iov_base=": ", iov_len=2}, {iov_base="error while loading shared libraries", iov_len=36}, {iov_base=": ", iov_len=2}, {iov_base="libinotifytools.so.0", iov_len=20}, {iov_base=": ", iov_len=2}, {iov_base="cannot open shared object file", iov_len=30}, {iov_base=": ", iov_len=2}, {iov_base="No such file or directory", iov_len=25}, {iov_base="\n", iov_len=1}], 10inotifywait: error while loading shared libraries: libinotifytools.so.0: cannot open shared object file: No such file or directory
...
```

Which appears the correction here would be:
`ln -s /usr/lib64/libinotifytools.so.0.4.1 /usr/lib/libinotifytools.so.0`

Thanks to [this thread](https://lists.gnu.org/archive/html/automake/2007-12/msg00038.html).

**Comment by ericcurtin** [comment]
When you have two versions of the library installed you can get clases kindof annoying I know, one way to ensure it works is remove the old version.
