### ISSUE TITLE
Add an option to ignore directory changes for inotifywait

### ISSUE THREAD

**Issue by NikolayMetchev** [inotify-tools/inotify-tools#76]
It would be useful to have a command line option to filter only on changes of files (not directories) in the inotifywait tool.

Many thanks

**Comment by NullVoxPopuli** [comment]
I'd like to be able to filter out changes to the git directory. I'm using inotifywait as an easy "live reload" server

**Comment by ericcurtin** [comment]
@NullVoxPopuli we support that, just use `--exclude=.git` ... Although it's worth remembering git does a pretty good job of this itself, you could poll `git status` and such...

@NikolayMetchev things like `inotifywait $(find src -type f)` do what you are asking...

Mind if I close this?

**Comment by NikolayMetchev** [comment]
I opened it 3 years ago. I think I just forked the project and implemented it myself. You can close

**Comment by ericcurtin** [comment]
Very interesting a C# windows version! 🙂 Nice job! I'll close, feel free to open a pull request if there's functionality you'd like to add here @NikolayMetchev, especially stuff that cannot be achieved using simple command substitutions, pipes, xargs etc.

**Comment by ericcurtin** [comment]
I starred your repo inotify-win, I'd certainly be interested in collaborating with @NikolayMetchev  and @thekid in integrating windows filewatching apis in inotify-tools sometime
