### ISSUE TITLE
Static only build fails && cross-compilation fails

### ISSUE THREAD

**Issue by mdeweerd** [inotify-tools/inotify-tools#83]
inotify-tools-3.13

I did the following for a cross-compilation where CONFIGURE_FLAGS holds hosts, sysroot, and other flags..

./configure $CONFIGURE_FLAGS --prefix=${INSTALLDIR} --enable-static  --disable-maintainer-mode  --disable-shared

The goal of this configure is to avoid dynamic libraries which allows the installation of just one executeable without any special dependencies.

After bypassing a limitation with cross compiling in the configure file, the build failed due to symbols being present in multiple locations.
Information is provided below.

Changes to configure to bypass the check - I do not think that this check should stop the compilation:
```
{ echo "$as_me:$LINENO: checking whether sys/inotify.h actually works" >&5
 echo $ECHO_N "checking whether sys/inotify.h actually works... $ECHO_C" >&6; }
-if test "$cross_compiling" = yes; then
-  { { echo "$as_me:$LINENO: error: cannot run test program while cross compiling
-See \`config.log' for more details." >&5
-echo "$as_me: error: cannot run test program while cross compiling
-See \`config.log' for more details." >&2;}
-   { (exit 1); exit 1; }; }
-else
+if test yes = yes ; then
   cat >conftest.$ac_ext <<_ACEOF
```
Link error (some paths changed for privacy) - multiple definition of _niceassert and isdir.
```
/bin/bash ../libtool --tag=CC --mode=link arm-linux-gnueabihf-gcc -std=c99 -I../libinotifytools/src -L../libinotifytools/src -g -O2   -o inotifywait  inotifywait.o common.o ../libinotifytools/src/libinotifytools.la 
arm-linux-gnueabihf-gcc -std=c99 -I../libinotifytools/src -g -O2 -o inotifywait inotifywait.o common.o  -L..../3rdparty/inotify-tools-3.13/libinotifytools/src ../libinotifytools/src/.libs/libinotifytools.a  
../libinotifytools/src/.libs/libinotifytools.a(inotifytools.o): In function `_niceassert':
...../3rdparty/inotify-tools-3.13/libinotifytools/src/inotifytools.c:197: multiple definition of `_niceassert'
common.o:...../3rdparty/inotify-tools-3.13/src/common.c:112: first defined here
../libinotifytools/src/.libs/libinotifytools.a(inotifytools.o): In function `isdir':
..../3rdparty/inotify-tools-3.13/libinotifytools/src/inotifytools.c:1595: multiple definition of `isdir'
common.o:...../3rdparty/inotify-tools-3.13/src/common.c:44: first defined here
```

**Comment by ericcurtin** [comment]
Could you specify what $CONFIGURE_FLAGS was?

**Comment by mdeweerd** [comment]
This was the value for CONFIGURE_FLAGS:
```
--target=arm-linux-gnueabi --host=arm-linux-gnueabi --build=x86_64-linux --with-libtool-sysroot=/opt/ti-processor-sdk-linux-am335x-evm-03.03.00.04/linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi
```

This is my current full script to build, it builds because I removed the "--disable-shared" option.
```
#!/bin/bash

# Install protobuf-compiler on current host to provide protoc
# [Otherwise, compile protobuf for current host]
#sudo apt-get install protobuf-compiler

MYDIR=$(dirname $(realpath $0))
INSTALLDIR=$(realpath $MYDIR/../opt)
CFLAGS_FOR_HOST="${CFLAGS}"
unset CFLAGS
LDFLAGS_FOR_HOST="${LDFLAGS}"
unset LDFLAGS
CPPFLAGS_FOR_HOST="${CPPFLAGS}"
unset CPPFLAGS
CPATH_FOR_HOST="${CPATH}"
unset CPATH
CXXFLAGS_FOR_HOST="${CXXFLAGS}"
unset CXXFLAGS

env
make distclean
#./configure $CONFIGURE_FLAGS --prefix=${INSTALLDIR} --enable-static  --disable-maintainer-mode  --disable-shared
./configure $CONFIGURE_FLAGS --prefix=${INSTALLDIR} --enable-static  --disable-maintainer-mode

make -j 4
make
make install
```

The cross-compilation tools are available near the bottom of this page:
http://software-dl.ti.com/processor-sdk-rtos/esd/AM335X/03_03_00_04/index_FDS.html

**Comment by ericcurtin** [comment]
This file for installing the tools @mdeweerd? :)

http://software-dl.ti.com/processor-sdk-rtos/esd/AM335X/03_03_00_04/exports/ti-processor-sdk-rtos-am335x-evm-03.03.00.04-Linux-x86-Install.bin

**Comment by mdeweerd** [comment]
Yes.

**Comment by ericcurtin** [comment]
Love the way this issue was written like a true coder using logical AND && over bitwise AND. I often have a habit of doing that too when writing things in English by mistake lol

**Comment by mdeweerd** [comment]
;-) I thought it was a nice separator to distinguish two issues in one title.

**Comment by ericcurtin** [comment]
Great to hear your issue was solved, thanks for reporting!
