### ISSUE TITLE
Incrond rules not working with SFTP\SCP

### ISSUE THREAD

**Issue by artemkamolodets** [inotify-tools/inotify-tools#87]
Hello. I'm using incron rule: <some directory> IN_MOVED_TO <some script>. So when i copying a new file into the <some dir> the <some script> is triggering. It works fine in bash session. 
When i'm using WinSCP client (SCP or SFTP protocols) to copy a new file into the <some dir> - there is nothing happens, the rule that described in incrontab, don't triggers.
Any ideas? Please help.

**Comment by 813gan** [comment]
SFTP does not 'move' file, it _creates new file_ and fills it with data received from sender.
BTW this is inotify-tools repo, not incrond ;)

**Comment by artemkamolodets** [comment]
Hello, thank you for the reply. I was tryed to use IN_CREATE rule, but it doesn't help :<

**Comment by 813gan** [comment]
I would try `IN_ALL_EVENTS`; as [man](https://linux.die.net/man/5/incrontab) says this will report all events. Does other tools using inotify work? Does your kernel support inotify?

**Comment by artemkamolodets** [comment]
IN_ATTRIB - has resolved my issue. Thank you/
Have a nice day.
