### ISSUE TITLE
Add pid of accessing process 

### ISSUE THREAD

**Issue by henfri** [inotify-tools/inotify-tools#89]
Hello,

thanks for writing inotify tools!
I intend to find what's causing my drives to spin up regularly. For that, I use 
inotifywatch -v -e access -e modify -t 1800 -r /path

But that does not output the process that caused the access. 
Is it possible to get the pid of the accessing process?

Regards,
Hendrik

**Comment by 813gan** [comment]
According to [inotify manpage](http://man7.org/linux/man-pages/man7/inotify.7.html) section `Limitations and caveats` no.
