### ISSUE TITLE
inotifywait does not timeout when excluded file is being modified

### ISSUE THREAD

**Issue by manascii** [inotify-tools/inotify-tools#91]
I'm noticing an odd behavior where inotifywait does not timeout when a specified exclude file is consistently being modified at the same time.

For example, if I execute the following:

``
$ inotifywait --exclude "foo" -t 3 watchdir
``

everything works as expected. However, if `foo` is constantly being modified at the same time during the watch, say for example:

``
./watchdir$ while true ; do touch foo ; sleep 1 ; done
``

then inotifywait does not timeout after 3 seconds.

Is there some other way this should be done?

Thanks!

Andrew

**Comment by Zedsquared** [comment]
I also have noticed this, in my case it is a file that is modified once a minute that is preventing a two minute timeout.
