### ISSUE TITLE
some exclude definitions are ignored with --fromfile

### ISSUE THREAD

**Issue by Spacewalker2** [inotify-tools/inotify-tools#98]
I use `inotifywait --quiet --event CREATE --recursive --fromfile /etc/inotify` and it worked fine except the .viminfo.tmp file definition. I tried `@.*viminfo.tmp` and `@.*viminfo\.tmp` too without any success. What am I doing wrong? For me some examples in the manpage would be nice or some files in /usr/share/inotify-tools/examples.

/etc/inotify:
```
/home/user
@/home/user/.cache <-- directory
@/home/user/.calendars <-- directory
@/home/user/.viminfo.tmp
```

**Comment by qqliuxiaoran** [comment]
i have some question, version is 3.20.11.0

**Comment by qqliuxiaoran** [comment]
> I use `inotifywait --quiet --event CREATE --recursive --fromfile /etc/inotify` and it worked fine except the .viminfo.tmp file definition. I tried `@.*viminfo.tmp` and `@.*viminfo\.tmp` too without any success. What am I doing wrong? For me some examples in the manpage would be nice or some files in /usr/share/inotify-tools/examples.
> 
> /etc/inotify:
> 
> ```
> /home/user
> @/home/user/.cache <-- directory
> @/home/user/.calendars <-- directory
> @/home/user/.viminfo.tmp
> ```

Have you solved? I'd appreciate you answer this question
